// <auto-generated />
using System;
using CarStoreManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarStoreManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.HistoricoConsignacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UsuarioResponsavelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VeiculoConsignacaoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoConsignacaoId");

                    b.ToTable("HistoricosConsignacao");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.PagamentoProposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModoPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropostaVendaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecebidoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropostaVendaId");

                    b.ToTable("PagamentosProposta");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.PropostaVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataRespostaFinanciadora")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSolicitacaoFinanciamento")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModoPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropostaFinanciadoraTexto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VeiculoEntidadeTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VeiculoVendaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PropostasVenda");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.TermoEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdminRedatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssinaturaCpfCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssinaturaIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssinaturaNomeCliente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRedacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaEdicao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropostaVendaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextoTermo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenAssinatura")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropostaVendaId")
                        .IsUnique();

                    b.HasIndex("TokenAssinatura");

                    b.ToTable("TermosEntrega");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.VeiculoConsignacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Acessorios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cambio")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClienteProprietarioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Combustivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motorizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextoContrato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlContratoPdf")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendedorResponsavelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VeiculosConsignacao");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.VeiculoVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Acessorios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoUltimoIpvaPago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cambio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Combustivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Disponibilidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motorizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoTermoPreliminar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VeiculosVenda");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.Vistoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRealizada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropostaVendaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VistoriadorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropostaVendaId");

                    b.ToTable("Vistorias");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VeiculoVendaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoVendaId");

                    b.HasIndex("EntidadeTipo", "EntidadeId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Integracoes.AnuncioMercadoLivre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoriaML")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaSincronizacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemIdML")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingTypeML")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UltimoErro")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErroDetalheTecnico")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UltimoPrecoSincronizado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemIdML");

                    b.HasIndex("EntidadeTipo", "EntidadeId")
                        .IsUnique();

                    b.ToTable("AnunciosMercadoLivre");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Integracoes.ConfiguracaoMercadoLivre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessTokenCriptografado")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Conectado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConexao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataExpiracaoToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailContaConectada")
                        .HasColumnType("TEXT");

                    b.Property<string>("MercadoLivreUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshTokenCriptografado")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegredoWebhook")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesMercadoLivre");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Integracoes.VendaMercadoLivre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnuncioMercadoLivreId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErroSincronizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdItemPlataforma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdPedidoPlataforma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusSincronizacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdPedidoPlataforma", "IdItemPlataforma")
                        .IsUnique();

                    b.ToTable("VendasMercadoLivre");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.AlertaOS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MecanicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacaoCliente")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvidoPor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.HasIndex("Status");

                    b.ToTable("AlertasOS");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ChecklistOrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("ChecklistItens");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ChecklistPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChecklistPresets");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ChecklistPresetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChecklistPresetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistPresetId");

                    b.ToTable("ChecklistPresetItens");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.Componente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEST")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoOEM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GarantiaDias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarcaFabricante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MargemLucroPct")
                        .HasPrecision(7, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("NCM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<string>("SKUInterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sistema")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Componentes");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ComponenteEquivalente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponenteEquivalenteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponenteOriginalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoEquivalencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteEquivalenteId");

                    b.HasIndex("ComponenteOriginalId");

                    b.ToTable("ComponenteEquivalente");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.EstoqueComponente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PecaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PecaId")
                        .IsUnique();

                    b.ToTable("EstoqueComponentes");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ItemOrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComponenteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoLivre")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusItem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("ItensOrdemServico");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MecanicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroPublico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrazoEstimado")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusAnterior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VeiculoClienteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NumeroPublico")
                        .IsUnique();

                    b.HasIndex("VeiculoClienteId");

                    b.ToTable("OrdensServico");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.PagamentoOrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModoPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecebidoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("PagamentosOrdemServico");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.RequisicaoPecaOS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComponenteAtendidoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoPeca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MecanicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacaoAdmin")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ResolvidaPor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.HasIndex("Status");

                    b.ToTable("RequisicoesPeca");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.VeiculoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VeiculosCliente");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Sistema.ConfiguracaoSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExigirEntradaMinima")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MargemPadraoGlobalPct")
                        .HasPrecision(7, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("MargensPorSistemaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentualEntradaMinima")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesSistema");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Sistema.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Geral");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Outros");

                    b.HasKey("Id");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Sistema.TemplateDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TemplatesDocumento");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("CarStoreManager.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.GerenteVendas", b =>
                {
                    b.HasBaseType("CarStoreManager.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("GerenteVendas");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.Vendedor", b =>
                {
                    b.HasBaseType("CarStoreManager.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Vendedor");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ChefeOficina", b =>
                {
                    b.HasBaseType("CarStoreManager.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("ChefeOficina");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.Mecanico", b =>
                {
                    b.HasBaseType("CarStoreManager.Domain.Entities.Usuario");

                    b.Property<int>("Especialidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocupado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrabalhosAtivos")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TrabalhosAtivos");

                    b.HasDiscriminator().HasValue("Mecanico");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Recepcionista", b =>
                {
                    b.HasBaseType("CarStoreManager.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Recepcionista");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("CarStoreManager.Domain.Entities.Cliente", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Telefone");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CPF");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.HistoricoConsignacao", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Concessionaria.VeiculoConsignacao", null)
                        .WithMany("Historico")
                        .HasForeignKey("VeiculoConsignacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.PagamentoProposta", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "Valor", b1 =>
                        {
                            b1.Property<Guid>("PagamentoPropostaId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Valor");

                            b1.HasKey("PagamentoPropostaId");

                            b1.ToTable("PagamentosProposta");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoPropostaId");
                        });

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.PropostaVenda", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Percentual", "Desconto", b1 =>
                        {
                            b1.Property<Guid>("PropostaVendaId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("TEXT")
                                .HasColumnName("DescontoPercentual");

                            b1.HasKey("PropostaVendaId");

                            b1.ToTable("PropostasVenda");

                            b1.WithOwner()
                                .HasForeignKey("PropostaVendaId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "Entrada", b1 =>
                        {
                            b1.Property<Guid>("PropostaVendaId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Entrada");

                            b1.HasKey("PropostaVendaId");

                            b1.ToTable("PropostasVenda");

                            b1.WithOwner()
                                .HasForeignKey("PropostaVendaId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "ValorBase", b1 =>
                        {
                            b1.Property<Guid>("PropostaVendaId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("ValorBase");

                            b1.HasKey("PropostaVendaId");

                            b1.ToTable("PropostasVenda");

                            b1.WithOwner()
                                .HasForeignKey("PropostaVendaId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "ValorFinal", b1 =>
                        {
                            b1.Property<Guid>("PropostaVendaId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("ValorFinal");

                            b1.HasKey("PropostaVendaId");

                            b1.ToTable("PropostasVenda");

                            b1.WithOwner()
                                .HasForeignKey("PropostaVendaId");
                        });

                    b.Navigation("Desconto")
                        .IsRequired();

                    b.Navigation("Entrada")
                        .IsRequired();

                    b.Navigation("ValorBase")
                        .IsRequired();

                    b.Navigation("ValorFinal")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.VeiculoConsignacao", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Ano", "Ano", b1 =>
                        {
                            b1.Property<Guid>("VeiculoConsignacaoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Valor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Ano");

                            b1.HasKey("VeiculoConsignacaoId");

                            b1.ToTable("VeiculosConsignacao");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoConsignacaoId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.PlacaVeiculo", "Placa", b1 =>
                        {
                            b1.Property<Guid>("VeiculoConsignacaoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Placa");

                            b1.HasKey("VeiculoConsignacaoId");

                            b1.ToTable("VeiculosConsignacao");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoConsignacaoId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Quilometragem", "Quilometragem", b1 =>
                        {
                            b1.Property<Guid>("VeiculoConsignacaoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Valor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quilometragem");

                            b1.HasKey("VeiculoConsignacaoId");

                            b1.ToTable("VeiculosConsignacao");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoConsignacaoId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Renavam", "Renavam", b1 =>
                        {
                            b1.Property<Guid>("VeiculoConsignacaoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Renavam");

                            b1.HasKey("VeiculoConsignacaoId");

                            b1.ToTable("VeiculosConsignacao");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoConsignacaoId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.ComissaoConsignacao", "Comissao", b1 =>
                        {
                            b1.Property<Guid>("VeiculoConsignacaoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Tipo")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ComissaoTipo");

                            b1.HasKey("VeiculoConsignacaoId");

                            b1.ToTable("VeiculosConsignacao");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoConsignacaoId");

                            b1.OwnsOne("CarStoreManager.Domain.ValueObjects.Percentual", "PorcentagemProprietario", b2 =>
                                {
                                    b2.Property<Guid>("ComissaoConsignacaoVeiculoConsignacaoId")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Valor")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ComissaoPorcentagemProprietario");

                                    b2.HasKey("ComissaoConsignacaoVeiculoConsignacaoId");

                                    b2.ToTable("VeiculosConsignacao");

                                    b2.WithOwner()
                                        .HasForeignKey("ComissaoConsignacaoVeiculoConsignacaoId");
                                });

                            b1.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "ValorFixoProprietario", b2 =>
                                {
                                    b2.Property<Guid>("ComissaoConsignacaoVeiculoConsignacaoId")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Valor")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ComissaoValorFixoProprietario");

                                    b2.HasKey("ComissaoConsignacaoVeiculoConsignacaoId");

                                    b2.ToTable("VeiculosConsignacao");

                                    b2.WithOwner()
                                        .HasForeignKey("ComissaoConsignacaoVeiculoConsignacaoId");
                                });

                            b1.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "ValorVendaEsperado", b2 =>
                                {
                                    b2.Property<Guid>("ComissaoConsignacaoVeiculoConsignacaoId")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Valor")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ValorVendaEsperado");

                                    b2.HasKey("ComissaoConsignacaoVeiculoConsignacaoId");

                                    b2.ToTable("VeiculosConsignacao");

                                    b2.WithOwner()
                                        .HasForeignKey("ComissaoConsignacaoVeiculoConsignacaoId");
                                });

                            b1.Navigation("PorcentagemProprietario");

                            b1.Navigation("ValorFixoProprietario");

                            b1.Navigation("ValorVendaEsperado")
                                .IsRequired();
                        });

                    b.Navigation("Ano")
                        .IsRequired();

                    b.Navigation("Comissao")
                        .IsRequired();

                    b.Navigation("Placa")
                        .IsRequired();

                    b.Navigation("Quilometragem")
                        .IsRequired();

                    b.Navigation("Renavam")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.VeiculoVenda", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Ano", "Ano", b1 =>
                        {
                            b1.Property<Guid>("VeiculoVendaId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Valor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Ano");

                            b1.HasKey("VeiculoVendaId");

                            b1.ToTable("VeiculosVenda");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoVendaId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.PlacaVeiculo", "Placa", b1 =>
                        {
                            b1.Property<Guid>("VeiculoVendaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Placa");

                            b1.HasKey("VeiculoVendaId");

                            b1.ToTable("VeiculosVenda");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoVendaId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Quilometragem", "Quilometragem", b1 =>
                        {
                            b1.Property<Guid>("VeiculoVendaId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Valor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quilometragem");

                            b1.HasKey("VeiculoVendaId");

                            b1.ToTable("VeiculosVenda");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoVendaId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Renavam", "Renavam", b1 =>
                        {
                            b1.Property<Guid>("VeiculoVendaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Renavam");

                            b1.HasKey("VeiculoVendaId");

                            b1.ToTable("VeiculosVenda");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoVendaId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "Valor", b1 =>
                        {
                            b1.Property<Guid>("VeiculoVendaId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("TEXT")
                                .HasColumnName("Valor");

                            b1.HasKey("VeiculoVendaId");

                            b1.ToTable("VeiculosVenda");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoVendaId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "ValorAquisicao", b1 =>
                        {
                            b1.Property<Guid>("VeiculoVendaId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("TEXT")
                                .HasColumnName("ValorAquisicao");

                            b1.HasKey("VeiculoVendaId");

                            b1.ToTable("VeiculosVenda");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoVendaId");
                        });

                    b.Navigation("Ano")
                        .IsRequired();

                    b.Navigation("Placa")
                        .IsRequired();

                    b.Navigation("Quilometragem")
                        .IsRequired();

                    b.Navigation("Renavam")
                        .IsRequired();

                    b.Navigation("Valor")
                        .IsRequired();

                    b.Navigation("ValorAquisicao")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Foto", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Concessionaria.VeiculoVenda", null)
                        .WithMany("Fotos")
                        .HasForeignKey("VeiculoVendaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ChecklistOrdemServico", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Oficina.OrdemServico", null)
                        .WithMany("Checklist")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ChecklistPresetItem", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Oficina.ChecklistPreset", null)
                        .WithMany("Itens")
                        .HasForeignKey("ChecklistPresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.Componente", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Oficina.Fornecedor", null)
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ComponenteEquivalente", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Oficina.Componente", "ComponenteEquivalenteRelacionado")
                        .WithMany("EquivalenciasRelacionadas")
                        .HasForeignKey("ComponenteEquivalenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarStoreManager.Domain.Entities.Oficina.Componente", "ComponenteOriginal")
                        .WithMany("EquivalenciasOriginais")
                        .HasForeignKey("ComponenteOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComponenteEquivalenteRelacionado");

                    b.Navigation("ComponenteOriginal");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.EstoqueComponente", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Oficina.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Componente");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.Fornecedor", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("CarStoreManager.Domain.Entities.Oficina.Fornecedor", "EnderecoId");

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("FornecedorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CNPJ");

                            b1.HasKey("FornecedorId");

                            b1.ToTable("Fornecedores");

                            b1.WithOwner()
                                .HasForeignKey("FornecedorId");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ItemOrdemServico", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Oficina.OrdemServico", null)
                        .WithMany("Itens")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "ValorTotal", b1 =>
                        {
                            b1.Property<Guid>("ItemOrdemServicoId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("TEXT")
                                .HasColumnName("ValorTotalItem");

                            b1.HasKey("ItemOrdemServicoId");

                            b1.ToTable("ItensOrdemServico");

                            b1.WithOwner()
                                .HasForeignKey("ItemOrdemServicoId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "ValorUnitario", b1 =>
                        {
                            b1.Property<Guid>("ItemOrdemServicoId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("TEXT")
                                .HasColumnName("ValorUnitario");

                            b1.HasKey("ItemOrdemServicoId");

                            b1.ToTable("ItensOrdemServico");

                            b1.WithOwner()
                                .HasForeignKey("ItemOrdemServicoId");
                        });

                    b.Navigation("ValorTotal")
                        .IsRequired();

                    b.Navigation("ValorUnitario")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.OrdemServico", b =>
                {
                    b.HasOne("CarStoreManager.Domain.Entities.Oficina.VeiculoCliente", null)
                        .WithMany("HistoricoServicos")
                        .HasForeignKey("VeiculoClienteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "CustoServico", b1 =>
                        {
                            b1.Property<Guid>("OrdemServicoId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("TEXT")
                                .HasColumnName("CustoServico");

                            b1.HasKey("OrdemServicoId");

                            b1.ToTable("OrdensServico");

                            b1.WithOwner()
                                .HasForeignKey("OrdemServicoId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "ValorTotal", b1 =>
                        {
                            b1.Property<Guid>("OrdemServicoId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("TEXT")
                                .HasColumnName("ValorTotal");

                            b1.HasKey("OrdemServicoId");

                            b1.ToTable("OrdensServico");

                            b1.WithOwner()
                                .HasForeignKey("OrdemServicoId");
                        });

                    b.Navigation("CustoServico")
                        .IsRequired();

                    b.Navigation("ValorTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.PagamentoOrdemServico", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "Valor", b1 =>
                        {
                            b1.Property<Guid>("PagamentoOrdemServicoId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Valor");

                            b1.HasKey("PagamentoOrdemServicoId");

                            b1.ToTable("PagamentosOrdemServico");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoOrdemServicoId");
                        });

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.VeiculoCliente", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Ano", "Ano", b1 =>
                        {
                            b1.Property<Guid>("VeiculoClienteId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Valor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Ano");

                            b1.HasKey("VeiculoClienteId");

                            b1.ToTable("VeiculosCliente");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoClienteId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.PlacaVeiculo", "Placa", b1 =>
                        {
                            b1.Property<Guid>("VeiculoClienteId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Placa");

                            b1.HasKey("VeiculoClienteId");

                            b1.ToTable("VeiculosCliente");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoClienteId");
                        });

                    b.Navigation("Ano")
                        .IsRequired();

                    b.Navigation("Placa")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Sistema.Despesa", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Dinheiro", "Valor", b1 =>
                        {
                            b1.Property<Guid>("DespesaId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Valor");

                            b1.HasKey("DespesaId");

                            b1.ToTable("Despesas");

                            b1.WithOwner()
                                .HasForeignKey("DespesaId");
                        });

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Telefone");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.Senha", "Senha", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("SenhaHash");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.GerenteVendas", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.DadosFuncionario", "DadosFuncionario", b1 =>
                        {
                            b1.Property<Guid>("GerenteVendasId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataContratacao")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("TEXT")
                                .HasColumnName("DataContratacao");

                            b1.Property<int>("Nivel")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("INTEGER")
                                .HasColumnName("Nivel");

                            b1.HasKey("GerenteVendasId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("GerenteVendasId");
                        });

                    b.Navigation("DadosFuncionario")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.Vendedor", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.DadosFuncionario", "DadosFuncionario", b1 =>
                        {
                            b1.Property<Guid>("VendedorId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataContratacao")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("TEXT")
                                .HasColumnName("DataContratacao");

                            b1.Property<int>("Nivel")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("INTEGER")
                                .HasColumnName("Nivel");

                            b1.HasKey("VendedorId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("VendedorId");
                        });

                    b.Navigation("DadosFuncionario")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ChefeOficina", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.DadosFuncionario", "DadosFuncionario", b1 =>
                        {
                            b1.Property<Guid>("ChefeOficinaId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataContratacao")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("TEXT")
                                .HasColumnName("DataContratacao");

                            b1.Property<int>("Nivel")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("INTEGER")
                                .HasColumnName("Nivel");

                            b1.HasKey("ChefeOficinaId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("ChefeOficinaId");
                        });

                    b.Navigation("DadosFuncionario")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.Mecanico", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.DadosFuncionario", "DadosFuncionario", b1 =>
                        {
                            b1.Property<Guid>("MecanicoId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataContratacao")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("TEXT")
                                .HasColumnName("DataContratacao");

                            b1.Property<int>("Nivel")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("INTEGER")
                                .HasColumnName("Nivel");

                            b1.HasKey("MecanicoId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("MecanicoId");
                        });

                    b.Navigation("DadosFuncionario")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Recepcionista", b =>
                {
                    b.OwnsOne("CarStoreManager.Domain.ValueObjects.DadosFuncionario", "DadosFuncionario", b1 =>
                        {
                            b1.Property<Guid>("RecepcionistaId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataContratacao")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("TEXT")
                                .HasColumnName("DataContratacao");

                            b1.Property<int>("Nivel")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("INTEGER")
                                .HasColumnName("Nivel");

                            b1.HasKey("RecepcionistaId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("RecepcionistaId");
                        });

                    b.Navigation("DadosFuncionario")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.VeiculoConsignacao", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Concessionaria.VeiculoVenda", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.ChecklistPreset", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.Componente", b =>
                {
                    b.Navigation("EquivalenciasOriginais");

                    b.Navigation("EquivalenciasRelacionadas");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.OrdemServico", b =>
                {
                    b.Navigation("Checklist");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CarStoreManager.Domain.Entities.Oficina.VeiculoCliente", b =>
                {
                    b.Navigation("HistoricoServicos");
                });
#pragma warning restore 612, 618
        }
    }
}
